version: '3.4'
services:
  dev-dlq-manager:
    image: dlq-manager
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:80
    volumes:
      - ./:/app
    environment:
      - FLASK_ENV=development
      - DATABASE_URI=
